### PR TITLE
Support Kobo Elipsa 2E

### PR DESCRIPTION
**Pull request by ivy-rew**
Thanks a lot for your hint on copying from Plato. I thought I'd have to spend many hours to get Elipsa2E support, now it was done in 5 minutes. Great teamwork :handshake: 

adapted from https://github.com/baskerville/plato/commit/162aafb1ed61fb4e46bc9e11e6654d1ac007a317 / https://github.com/baskerville/plato/issues/315 many thanks to @baskerville

Me, working in the sun with a sharp ein-vnc screen. :sun_with_face:  :fallen_leaf: 
Imagepipe_35

### CODE REVIEW

**Comment by everydayanchovies** [comment]
Sick! How's the experience on a big screen? Could you post a video?

I might upgrade eventually.

Thanks for the patch. Cheers Max

**Comment by ivy-rew** [comment]
the elipsa2e with einkvnc in action:
https://github.com/user-attachments/assets/36a8bc7c-2e39-44a2-8967-47bf08c79403

**Comment by ivy-rew** [comment]
I'm fascinated too by the possibilities of the Elipsa2e @everydayanchovies 

To get a better feeling on the size of the screen. On the left is the Kobo Elipsa2E (10,3), and on the right is my older Kobo Libra H20 (7).

Imagepipe_36

The downside of the setup compared to H20 and other more popular devices, the Elipsa has a new board and usb-net drivers are not included. I'm not aware of a solution yet to support it as on other devices. So I have to stick the using W-LAN ... which limits the off grid use-cases

**Comment by ivy-rew** [comment]
And the last important note on the setup: @glowmouse made the VNC client compatible with tigervncserver, which is much more performant and compatible than tightvncserver ... at least on my host (Ubuntu 24.04). ... I'll soon send you a PR on that topic :blush:

**Pull request merged**
